### ISSUE TITLE
安装时错误

### ISSUE THREAD

**Issue by compass-yan** [iweizime/WechatStepChanger#1]
## 解析包时出错

**Comment by iweizime** [comment]
@sesamefly 我自己是Android 7.x系统，所以编译的时候只支持了7.x，你是哪个版本的

**Comment by iweizime** [comment]
@sesamefly 改成了最低支持Android 5.1系统，你可以重新试一下

**Comment by compass-yan** [comment]
好的。谢谢，我先试一试。

**Comment by compass-yan** [comment]
![image](https://user-images.githubusercontent.com/22750919/29076206-595de904-7c87-11e7-95c6-c12b45de1262.png)
 安装包异常，是安装这个app么
