### ISSUE TITLE
红米2a，root，授予权限后，canread返回false。一直不能读取。

### ISSUE THREAD

**Issue by df13954** [iweizime/WechatStepChanger#4]

**Comment by iweizime** [comment]
你是MIUI开发版自带的Root还是SuperSu，有的su支持的命令少，你可以用ADB shell手动给一下读写权限
chmod o+rw /data/data/com.tencent.mm/MicroMsg/stepcounter.cfg
chmod o+x /data/data/com.tencent.mm/MicroMsg/

**Comment by df13954** [comment]
开发版本自带，执行之后bad mode。。晕，现在用原生的Android 7.0，可以load，但是保存之后，打开微信，步数没有修改，然后步数一直停滞了。

**Comment by iweizime** [comment]
微信步数的数据来源要选择“我的手机”，我之前数据来源选择小米手环也没效果。但是好像红米2A好像并没有Step Counter Sensor

**Comment by df13954** [comment]
红米2A没有，对的，现在我用nexus 5x Android 7.0 。数据来源要选择“我的手机”，然后能load出步数，但是修改步数之后，就没有更新步数了。不管我怎么走路运动，都停止在修改前的那个数值。
不知道是不是微信修改了策略。微信6.5.8

**Comment by iweizime** [comment]
这个我也说不清楚，我自己的是小米6 Android 7.1.1，微信6.5.10，是有效的。你改完之后再load，出来的数据是改之前的还是之后的，如果是之后的，那就说明改成功了。还有改的时候改的不要太多，而且只能增大不能减小。再不行我也不清楚了

**Comment by df13954** [comment]
我第一次load 是正确修改完成之后，再load，返回0、我先升级到6510试试。可能我修改的步数太夸张了。哈哈

**Comment by iweizime** [comment]
自己试过4w，再高就没试过了。你改成了多少

**Comment by df13954** [comment]
我的微信是658，点击更新提示最新版，现在Google play上面的是6510.我现在试试修改，我都是设置5w+。哈哈

**Comment by df13954** [comment]
是先杀死微信，在load，修改，保存，再打开微信？这个流程

**Comment by iweizime** [comment]
不用，最简单的只需要load/store就可以了，程序会自己杀死微信进程

**Comment by df13954** [comment]
O(∩_∩)O哈哈~，nice，nice。可以啦，修改的幅度不能太多。赞

**Comment by iweizime** [comment]
嗯，我刚试了一下，一下子改到5W，也是不行的，应该是有异常检测

**Comment by df13954** [comment]
可以在md中提醒下。

**Comment by iweizime** [comment]
好的
