### ISSUE TITLE
支付宝的运动怎么改

### ISSUE THREAD

**Issue by drcege** [iweizime/WechatStepChanger#5]
支付宝的运动跟这类似吗，有研究过可以不用xposed直接root修改吗

**Comment by iweizime** [comment]
支付宝可能有不同的计步方式，一种是给它后台运行权限，它自己根据Step Counter Sensor计步，还有一种是它不会一直后台运行，根据系统提供的数据计步。在MIUI系统上，有一个com.miui.stepsprovider.StepApplication的程序负责计步，计步结果保存在数据库Steps.db里，修改这个数据库就可以了。不一定准确，给你参考一下，我也没有弄清楚
